# Generated by Django 2.0.1 on 2018-01-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='about',
            field=models.TextField(default='This book is about...', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='current_loc',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='file_url',
            field=models.URLField(default='http://...'),
            preserve_default=False,
        ),
    ]
