# Generated by Django 2.0.1 on 2018-01-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180102_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='current_loc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='file_url',
            field=models.URLField(default=''),
        ),
    ]
