# Generated by Django 2.0.1 on 2018-01-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='book',
            name='file_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
