# Generated by Django 2.0.1 on 2018-01-02 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20180102_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='udpated_at',
            new_name='updated_at',
        ),
    ]
