# Generated by Django 2.0.1 on 2018-01-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20180103_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='upload',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
