# Generated by Django 2.0.1 on 2018-01-07 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20180107_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='file_url',
        ),
    ]
