# Generated by Django 2.0.1 on 2018-01-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_remove_book_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='current_loc',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
