# Generated by Django 2.0.1 on 2018-05-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_auto_20180108_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='current_loc_folio',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
